// https://opentelemetry.io/docs/specs/otel/logs/data-model/

export interface Happening {
  eventAt: Date,
  appName: string,
  eventCategory: string,
  eventCode: string,
  eventValue?: string,
  // eventName?: string,
  description?: string,
  resourceType?: string,
  resourceAction?: string,
  subResource?: string,
  resourceResult?: string,
  resourceId?: string,
  resourceInstanceName?: string,
  initiatorAction?: string,
  param?: string,
  param2?: string,  
  param3?: string,  
  referrer?: string,
  groupId?: string,
  snapshotGroupName?: string, 
  userId?: string,
  snapshotUserName?: string,
  subResourceId?: string,
  userAgent?: string,
  ipAddress?: string,
  derivedUserAgent?: string,
  derivedIpAddress?: string,
  tags?: string,
  browser?: string,
  os?: string,
  reason?: string,
  comment?: string,
  exceptionName?: string,
  appVersion?: string,
  source?: string,
  target?: string,
  eventId?: string,
  document?: string,
  authToken?: string,
  sessionId?: string,
  uniqueBrowserToken?: string
  recordCreatedAt?: Date,   // This is the timestamp.
  serverName?: string,
  responseCode?: number,
  batchStamp?: string,
  postalCode?: string,
  latitude?: string,
  longitude?: string,
  city?: string,
  region?: string,
  country?: string,  
  screenHeight?: number,
  screenWidth?: number,
  upstreamRecordId?: string, 
  attributes: { [key: string]: string | number | boolean }
  spanId?: string,
  traceId?: string,
  severity?: string,
  duration?: number
}